volumes:
  db_data:
  redis_data:
  tap_data:

services:
  db:
    image: postgres:16-alpine
    ports:
      - 5432:5432
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=password
  redis:
    image: redis:7
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    ports:
      - 6379:6379
  tap:
    image: ghcr.io/bluesky-social/indigo/tap:0.1
    environment:
      - TAP_DATABASE_URL=sqlite:///data/tap.db
    volumes:
      - tap_data:/data
    ports:
      - 2480:2480
  atblob:
    image: ghcr.io/mkizka/atblob:latest
    environment:
      - PORT=3002
      - DID_CACHE=redis
      - REDIS_URL=redis://redis:6379
    depends_on:
      - redis
    ports:
      - 3002:3002
