volumes:
  db_data:

services:
  db:
    image: postgres:16-alpine
    ports:
      - 5432:5432
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=password
  jetstream:
    image: ghcr.io/bluesky-social/jetstream:sha-ea96859
    restart: always
    network_mode: host
    environment:
      - JETSTREAM_WS_URL=ws://localhost:2583/xrpc/com.atproto.sync.subscribeRepos
      - JETSTREAM_WORKER_COUNT=1
      - JETSTREAM_LIVENESS_TTL=10m
