volumes:
  db_data:

services:
  db:
    image: mysql:9
    ports:
      - 3306:3306
    volumes:
      - db_data:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=db
      - MYSQL_ROOT_PASSWORD=password
  jetstream:
    image: ghcr.io/bluesky-social/jetstream:sha-ea96859
    restart: always
    network_mode: host
    environment:
      - JETSTREAM_WS_URL=ws://localhost:2583/xrpc/com.atproto.sync.subscribeRepos
      - JETSTREAM_WORKER_COUNT=1
      - JETSTREAM_LIVENESS_TTL=10m
