import "./globals.css";

import type { Metadata } from "next";
import { Murecho } from "next/font/google";

import FlyonuiScript from "./_components/FlyonScript";

const murecho = Murecho({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <body className={murecho.className}>
        {children}
        <FlyonuiScript />
      </body>
    </html>
  );
}
