name: Docker Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          - appview
          - admin
          - blob-proxy
          - ingester
          - worker
    steps:
      - uses: actions/checkout@v4
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/setup-buildx-action@v3
      - uses: docker/build-push-action@v6
        with:
          push: true
          build-args: |
            TARGET=${{ matrix.target }}
          tags: ghcr.io/${{ github.repository }}-${{ matrix.target }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
